{% set name = "numpyro" %}
{% set version = "0.15.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://github.com/pyro-ppl/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: b8fbcc259575dfb9068e947015acde42b389772141a0d24acc640d2335e16d99

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  # Missing jax and jaxlib python version 3.9
  # https://github.com/jax-ml/jax/blob/jax-v0.4.35/setup.py#L118
  # Missing jax and jaxlib for s390x
  # The numpyro max version python 3.11
  skip: True  # [py<=39 or py>311 or s390x]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    # Jax v0.4.35 is not support python 3.9
    # https://github.com/jax-ml/jax/blob/jax-v0.4.35/setup.py#L118
    # If we need to add compatibility with python3.9 we must add Jax v0.4.25
    # https://github.com/jax-ml/jax/blob/jax-v0.4.25/setup.py#L188
    - jax >=0.4.25
    - jaxlib >=0.4.25
    - multipledispatch
    - numpy
    - tqdm

test:
  source_files:
    - test
    - examples
  imports:
    - numpyro
  commands:
    - pip check
    # test/contrib:
    # funsor >=0.4.1, flax, dm-haiku missin
    - pytest -v
      --ignore=test/contrib/test_infer_discrete.py
      --ignore=test/contrib/test_funsor.py
      --ignore=test/contrib/test_enum_elbo.py
      --ignore=test/contrib/test_esc_proxies.py
      --ignore=test/contrib/einstein/test_mixture_guide_predictive.py
      --ignore=test/contrib/einstein/test_stein_kernels.py
      --ignore=test/contrib/einstein/test_steinvi.py
      --ignore=test/contrib/einstein/test_stein_loss.py
      --ignore=test/contrib/einstein/test_steinvi_util.py
      --ignore=test/contrib/test_module.py
      --ignore=test/contrib/test_nested_sampling.py
      --ignore=test/contrib/test_tfp.py
      --ignore=test/contrib/hsgp/test_approximation.py
      --ignore=test/contrib/hsgp/test_spectral_densities.py
      --ignore=test/contrib/stochastic_support/test_sdvi.py
        test/contrib
    # test/infer:
    # funsor >=0.4.1(all_platforms) and optax(win-64) missing
    - pytest -v
      --ignore=test/infer/test_gradient.py
      --ignore=test/infer/test_autoguide.py
      --ignore=test/infer/test_hmc_gibbs.py
      --ignore=test/infer/test_infer_util.py
      --ignore=test/infer/test_mcmc.py
      --ignore=test/infer/test_svi.py
        test/infer
    # test/ops:
    - pytest -v test/ops
    # test/pyroapi:
    # pyro-api >=0.1.1 missing
    #- pytest -v --ignore=test/pyroapi/test_pyroapi.py test/pyroapi #Disabled. Reason - only 1 file inside
    - pytest -v test/test_compile.py
    - pytest -v test/test_constraints.py
    - pytest -v test/test_diagnostics.py
    - pytest -v test/test_distributions_mixture.py
    # funsor >=0.4.1 missing
    #- pytest -v --ignore=test/test_distributions.py test/test_distributions.py #Disabled. Reason - ignored file
    # tensorflow_probability >=0.18.0 missing
    - pytest -v --deselect=test/test_distributions_util.py::test_no_tracer_leak_at_lazy_property_sample test/test_distributions_util.py
    # funsor >=0.4.1 missing
    #- pytest -v --ignore=test/test_examples.py test/test_examples.py #Disabled. Reason - ignored file
    - pytest -v test/test_example_utils.py
    - pytest -v test/test_flows.py
    - pytest -v test/test_handlers.py
    # graphviz missing
    - pytest -v
      --deselect=test/test_model_rendering.py::test_render_model_filename
        test/test_model_rendering.py
    - pytest -v test/test_nn.py
    # chex==0.1.84(all_platforms) and optax(win-64) missing
    #- pytest -v --ignore=test/test_optimizers.py test/test_optimizers.py #Disabled. Reason - ignored file
    # funsor >=0.4.1 missing
    #- pytest -v --ignore=test/test_pickle.py test/test_pickle.py #Disabled. Reason - ignored file
    - pytest -v test/test_transforms.py
    - pytest -v test/test_util.py
  requires:
    - pip
    - pytest
    - optax>=0.0.6 # [not win]
    - scikit-learn
    - matplotlib
    # Needs to run all tests:
    # - graphviz
    # - funsor >=0.4.1
    # - tensorflow_probability >=0.18.0
    # - pyro-api >=0.1.1
    # - flax
    # - dm-haiku
    # - chex==0.1.84

about:
  home: https://github.com/pyro-ppl/numpyro
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: Pyro PPL on NumPy
  doc_url: https://num.pyro.ai/en/stable/
  dev_url: https://github.com/pyro-ppl/numpyro
  description: Probabilistic programming powered by JAX for autograd and JIT compilation to GPU/TPU/CPU.

extra:
  recipe-maintainers:
    - fehiepsi
    - freddyaboulton
