{% set name = "numpyro" %}
{% set version = "0.15.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f445eeae6200f883d790d65ce29ff245f7a9639bac3322d993eccf91c44023b3

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  # Missing jax and jaxlib python version 3.9
  # https://github.com/jax-ml/jax/blob/jax-v0.4.35/setup.py#L118
  # Missing jax and jaxlib for s390x
  skip: True  # [py<=39 or py>311 or s390x]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    # Jax v0.4.35 is not support python 3.9
    # https://github.com/jax-ml/jax/blob/jax-v0.4.35/setup.py#L118
    # If we need to add compatibility with python3.9 we must add Jax v0.4.25
    # https://github.com/jax-ml/jax/blob/jax-v0.4.25/setup.py#L188
    - jax >=0.4.25 # [py>39]
    - jaxlib >=0.4.25 # [py>39]
    - multipledispatch
    - numpy
    - tqdm

# Skipped pytest by dependencies packages missing reason. 
# pyro-api >=0.1.1 and funsor >=0.4.1
test:
  imports:
    - numpyro
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyro-ppl/numpyro
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: Pyro PPL on NumPy
  doc_url: https://num.pyro.ai/en/stable/
  dev_url: https://github.com/pyro-ppl/numpyro
  description: Probabilistic programming powered by JAX for autograd and JIT compilation to GPU/TPU/CPU.

extra:
  recipe-maintainers:
    - fehiepsi
    - freddyaboulton
