{% set name = "numpyro" %}
{% set version = "0.15.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numpyro-{{ version }}.tar.gz
  sha256: f445eeae6200f883d790d65ce29ff245f7a9639bac3322d993eccf91c44023b3
  patches:
    - 0001-Lower-jax-constrains-in-setup.patch

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: True  # [py<39 or py>312]

requirements:
  build: 
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - wheel
  run:
    - python
    - jax >=0.4.23
    - jaxlib >=0.4.23
    - multipledispatch
    - numpy
    - tqdm
    - scipy <1.13

test:
  imports:
    - numpyro
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyro-ppl/numpyro
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: Pyro PPL on NumPy
  doc_url: https://num.pyro.ai/en/stable/
  dev_url: https://github.com/pyro-ppl/numpyro
  description: Probabilistic programming powered by JAX for autograd and JIT compilation to GPU/TPU/CPU.

extra:
  recipe-maintainers:
    - fehiepsi
    - freddyaboulton
